language: go
sudo: false

env:
  global:
  - GO111MODULE=on
  - NAME=brew-web

matrix:
  include:
    - go: 1.11.x

install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox
  - go get github.com/rakyll/statik
  - . $HOME/.nvm/nvm.sh
  - nvm install lst
  - nvm use lst
  - npm install

script:
- npm install --prefix web-ui
- npm run build --prefix web-ui
- go mod vendor
- go test ./...
- statik -src=web-ui/build
  # Only build binaries from the latest Go release.
- if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="brew-web.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi


# deploy:
#   provider: releases
#   skip_cleanup: true
#   api_key:
#     # Your *encrypted* GitHub key, as the output of the Travis CI CLI tool.
#     secure: GIT_HUB
#   file:
#   # The names of the binaries to output, based on the -output template passed to gox.
#   - logshare.windows.amd64.exe
#   - logshare.darwin.amd64
#   - logshare.linux.amd64
#   on:
#     repo: piotrjaromin/brew-web
#     # Only build binaries for tagged commits
#     tags: true
#     condition: $LATEST = true