
### Put in .vsocde/settings.json root
# "rest-client.environmentVariables": {
#     "$shared": {},
#     "local": {
#         "brewUrl": "http://localhost:80",
#     }
# },

### Enable heater1
# @name enableHeater1
POST {{brewUrl}}/heaters HTTP/1.1
Content-Type: application/json

{ "power": 1 }


### Get heater1
# @name getHeater1
GET {{brewUrl}}/heaters HTTP/1.1
Content-Type: application/json

### Get heater1
# @name getHeater1
GET {{brewUrl}}/temperatures HTTP/1.1
Content-Type: application/json



