---
- hosts: brewpi
  remote_user: root
  become: yes
  vars:
    workDir: /root
    user: root
    version: 0.4.6

  tasks:
  # - name: Install mdns
  #   shell: sudo apt-get install avahi-daemon
  # - name: Configure system
  #   shell: dtoverlay w1-gpio gpiopin=4
  - name: Download brew-web
    get_url:
      url: "https://github.com/piotrjaromin/brew-web/releases/download/{{ version }}/brew-web_{{ version }}_Linux_armv6.tar.gz"
      dest: "{{ workDir }}/brew-web.tar.gz"
      mode: '0777'
  - name: Extract
    unarchive:
      remote_src: yes
      src: "{{ workDir }}/brew-web.tar.gz"
      dest: "{{ workDir }}"
  - name: copy service file
    copy:
      src: ./brew.service
      dest: /lib/systemd/system
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'
  - name: copy config.yml
    copy:
      src: ../config.yml
      dest: "{{ workDir }}"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'
  - name: enable service brew
    systemd:
      name: brew
      enabled: yes
  - name: start bew service
    systemd:
      name: brew
      state: started