name: "build"
run-name: "Build ${{ github.sha }}"
on:
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    timeout-minutes: 25
    steps:
      - uses: "actions/checkout@v2"
      - run: "echo \"COMMIT_SHA=$(echo $GITHUB_SHA | cut -c 1-6)\" >> $GITHUB_ENV"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "buildbox"
        uses: "docker/setup-buildx-action@v1"
      - name: "docker push"
        env:
          REPOSITORY: "piotrjaromin/brew-web"
          IMAGE_TAG: "${{ github.sha }}"
        run: |
          docker buildx build \
          --platform "linux/arm64,linux/arm/v8" \
          --tag $REPOSITORY:${{ env.COMMIT_SHA }} \
          --output type=image,push=true .